#!/usr/bin/env python 
# -*- coding: utf-8 -*-
import unicodecsv, json, sys, codecs

input = codecs.open(sys.argv[1], 'r', encoding='utf8')
data = json.load(input)
input.close()

#sys.stdout = codecs.getwriter('utf8')
file = open(sys.argv[2], 'w')
output = unicodecsv.writer(file)
output.writerow(data[0].keys())  # header row

for row in data:
    output.writerow(row.values())

